// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.13.0

package postgres

import (
	"database/sql"
	"time"
)

type File struct {
	ID        int32
	TgID      sql.NullString
	Url       sql.NullString
	UserTgID  sql.NullInt64
	CreatedAt time.Time
}

type Message struct {
	ID        int32
	UserTgID  sql.NullInt64
	Text      sql.NullString
	CreatedAt time.Time
}

type User struct {
	ID        int32
	TgID      sql.NullInt64
	ChatID    sql.NullInt64
	Role      string
	FirstName sql.NullString
	LastName  sql.NullString
	UserName  sql.NullString
}
